# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.2
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=26.1-2.0.0-t2
maven_group=net.farzad.twisted_and_carved
archives_base_name=twisted_and_carved

# Dependencies
fabric_api_version=0.154.2+26.1.2
terrablender_version=26.1.0.2
chiseled_lib_version=2.0.2-26.1